# Generated by Django 3.2.4 on 2021-06-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=20)),
                ('Writter', models.CharField(max_length=30)),
                ('Published_Year', models.DateField()),
                ('No_of_Book', models.IntegerField()),
                ('Image_of_Book', models.ImageField(upload_to='')),
            ],
        ),
    ]
