# Generated by Django 2.1.4 on 2021-06-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210615_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='writter',
            new_name='author',
        ),
    ]
