# Generated by Django 2.1.4 on 2021-06-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210618_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image_of_book',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
